updated yaml files

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -1,28 +1,49 @@
-# GitHub Actions docs
-# https://help.github.com/en/articles/about-github-actions
-# https://help.github.com/en/articles/workflow-syntax-for-github-actions
-name: CI
+# Copyright 2022 Google LLC
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#      http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
 
-on: [push]
-
+on:
+  push:
+    branches:
+      - master
+  pull_request:
+name: code-coverage-check  
 jobs:
-  build:
+  coverage:
     runs-on: ubuntu-latest
-
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Set up Node.js
-      uses: actions/setup-node@v2
+    - uses: actions/checkout@v3
+    - uses: actions/setup-go@v2
       with:
-        node-version: 14  # Use the Node.js version required for your Angular project
+        go-version: '1.19'
 
-    - name: Install dependencies
+    - name: Unit tests
       run: |
-            cd ui
-            npm ci
-    - name: Run test
+            go test ./... -coverprofile coverage.out -covermode count
+            go tool cover -func coverage.out
+
+    - name: Quality Gate - Test coverage should be above threshold
+      env:
+          TESTCOVERAGE_THRESHOLD: 50
       run: |
-            cd ui
-            npm test -- --browsers=ChromeHeadless --watch=false
+            echo "Quality Gate: checking if test coverage is above threshold ..."
+            echo "Threshold             : $TESTCOVERAGE_THRESHOLD %"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Current test coverage : $totalCoverage %"
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
+                echo "OK"
+            else
+                echo "Current test coverage is below threshold. Please add more unit tests or adjust threshold to a lower value."
+                echo "Failed"
+                exit 1
+            fi
